# Generated by Django 2.2.5 on 2020-08-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200810_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='randomid',
            new_name='randomkey',
        ),
    ]
